function createfigure(cdata1, VertexNormals1, YData1, XData1, Vertices1, Faces1, FaceVertexCData1, cdata2, X1, Y1, X2)
%CREATEFIGURE(CDATA1,VERTEXNORMALS1,YDATA1,XDATA1,VERTICES1,FACES1,FACEVERTEXCDATA1,CDATA2,X1,Y1,X2)
%  CDATA1:  image cdata
%  VERTEXNORMALS1:  patch vertexnormals
%  YDATA1:  patch ydata
%  XDATA1:  patch xdata
%  VERTICES1:  patch vertices
%  FACES1:  patch faces
%  FACEVERTEXCDATA1:  patch facevertexcdata
%  CDATA2:  image cdata
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data

%  Auto-generated by MATLAB on 18-May-2012 17:39:07

% Create figure
figure1 = figure('Colormap',...
    [0.16666667163372 0 0;0.583333313465118 0 0;1 0 0;1 0.5 0;1 1 0;0.984670221805573 0.983244180679321 0.0713012516498566;0.969340443611145 0.966488420963287 0.142602503299713;0.954010725021362 0.949732601642609 0.213903740048409;0.938680946826935 0.932976841926575 0.285205006599426;0.923351168632507 0.916221022605896 0.356506258249283;0.90802139043808 0.899465262889862 0.427807480096817;0.892691612243652 0.882709443569183 0.499108731746674;0.877361834049225 0.865953683853149 0.570410013198853;0.862032115459442 0.849197864532471 0.641711235046387;0.846702337265015 0.832442104816437 0.713012516498566;0.831372559070587 0.815686285495758 0.7843137383461]);

% Create axes
axes1 = axes('Parent',figure1,...
    'XTickLabel',{'18:53','','','','','','','','','23:53'},...
    'Position',[0.264548611111111 0.11 0.236805555555556 0.815],...
    'Layer','top');
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[537069.757698346 547626.237374713]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[1.35 26]);
box(axes1,'on');
hold(axes1,'all');

% Create image
image(1,[1.6 30.6],cdata1,'Parent',axes1);

% Create patch
patch('Parent',axes1,'VertexNormals',VertexNormals1,'YData',YData1,...
    'XData',XData1,...
    'Vertices',Vertices1,...
    'Faces',Faces1,...
    'FaceColor',[0.380392163991928 0.380392163991928 0.380392163991928],...
    'FaceVertexCData',FaceVertexCData1,...
    'CData',FaceVertexCData1);

% Create xlabel
xlabel('Time');

% Create axes
axes2 = axes('Parent',figure1,...
    'XTickLabel',{'18:53','','','','','','','','','23:53'},...
    'Position',[0.533645833333333 0.11 0.236805555555556 0.815],...
    'Layer','top');
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[537069.757698346 547626.237374713]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[1.35 26]);
box(axes2,'on');
hold(axes2,'all');

% Create image
image(1,[1.6 30.6],cdata2,'Parent',axes2);

% Create patch
patch('Parent',axes2,'VertexNormals',VertexNormals1,'YData',YData1,...
    'XData',XData1,...
    'Vertices',Vertices1,...
    'Faces',Faces1,...
    'FaceColor',[0.313725501298904 0.313725501298904 0.313725501298904],...
    'FaceVertexCData',FaceVertexCData1,...
    'CData',FaceVertexCData1);

% Create xlabel
xlabel('Time');

% Create subplot
subplot1 = subplot(1,6,1,'Parent',figure1);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0 4.46748415266334]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[1.6 26]);
box(subplot1,'on');
hold(subplot1,'all');

% Create plot
plot(X1,Y1,'Parent',subplot1);

% Create xlabel
xlabel('Current Magnitude (m/s)');

% Create ylabel
ylabel('Height Above Bed (m)');

% Create subplot
subplot2 = subplot(1,6,6,'Parent',figure1);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[0 4.46748415266334]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[1.6 26]);
box(subplot2,'on');
hold(subplot2,'all');

% Create plot
plot(X2,Y1,'Parent',subplot2);

% Create xlabel
xlabel('Current Magnitude (m/s)');

