function mrg_newfunc
% Prompts for a new function name and location, and creates a MATLAB '.m'
% with pre-filled (boilerplate) text for documentation.
%
% INPUT
%   None. No input required.
%
% OUTPUT
%   No output at console. Generates a file with pre-filled (boilerplate)
%   text for function construction.  
%
% NOTES
%   This function is intended to aid in the development of functions for
%   the MRG toolbox by providing boilerplate text for important
%   documentation.  
%
% AUTHORS
%   Daniel Pritchard
%
% LICENCE
%   Code distributed as part of the MRG toolbox from the Marine Research
%   Group at Queens University Belfast (QUB) School of Planning
%   Architecture and Civil Engineering (SPACE). Distributed under a
%   creative commons CC BY-SA licence, retaining full copyright of the
%   original authors.
%
%   http://creativecommons.org/licenses/by-sa/3.0/
%   http://www.qub.ac.uk/space/
%   http://www.qub.ac.uk/research-centres/eerc/
%
% DEVELOPMENT
%   v 1.0   2013-08-15
%           First version. DP.
%           Documentation. DP.
%           corrected typos... BE
%

%%
[fname,fpath] = uiputfile('*.m', 'Enter a name and location for the function', 'mrg_FUNC_NAME.m');

bptext = ['function [OUT1, OUT2] = %s(IN1, IN2)\r\n',...
'%% DESCRIPTION. What does the function do?\r\n',...
'%%\r\n',...
'%% -- Read and Delete -- \r\n',...
'%% Please fill out the description line above and the sections below. At a\r\n',...
'%% minimum please document the INPUT and OUTPUT sections. If additional\r\n',...
'%% sections headings are justified (e.g WARNING) please add these too.\r\n',...
'%% -- Ends --\r\n',...
'%%\r\n',...
'%% INPUT\r\n',...
'%%   IN1   DESCRIPTION\r\n',...
'%%   IN2   DESCRIPTION\r\n',...
'%%\r\n',...
'%% OUTPUT\r\n',...
'%%   OUT1  DESCRIPTION\r\n',...
'%%   OUT2  DESCRIPTION\r\n',...
'%%   If no output please state: NO OUTPUT AT CONSOLE\r\n',...
'%%\r\n',...
'%% USAGE\r\n',...
'%%   Provide an example to show how the function should be used\r\n',...
'%%\r\n',...
'%% NOTES\r\n',...
'%%   Additional (more verbose) documentation can go here.\r\n',...
'%%\r\n',...
'%% REQUIREMENTS\r\n',...
'%%   List external toolboxes, platform dependencies etc here.\r\n',...
'%%   If external toolboxes are needed, please provide links and state what\r\n',...
'%%   version was used for development and testing.\r\n',...
'%%\r\n',...
'%% OCTAVE COMPATIBILITY\r\n',...
'%%   If your code is Octave compatible? Yes, No, or Untested.\r\n',...
'%%\r\n',...
'%% REFERENCES\r\n',...
'%%   Please list references here in a consistent, human readable format.\r\n',...
'%%\r\n',...
'%% AUTHORS\r\n',...
'%%   YOUR NAME HERE!\r\n',...
'%%\r\n',...
'%% LICENCE\r\n',...
'%%   Code distributed as part of the MRG toolbox from the Marine Research\r\n',... 
'%%   Group at Queens University Belfast (QUB) School of Planning\r\n',... 
'%%   Architecture and Civil Engineering (SPACE). Distributed under a\r\n',...
'%%   creative commons CC BY-SA licence, retaining full copyright of the\r\n',...
'%%   original authors.\r\n',...
'%%\r\n',...
'%%   http://creativecommons.org/licenses/by-sa/3.0/\r\n',...
'%%   http://www.qub.ac.uk/space/\r\n',...
'%%   http://www.qub.ac.uk/research-centres/eerc/\r\n',...
'%%\r\n',...
'%% DEVELOPMENT\r\n',...
'%%   v 1.0   YYYY-MM-DD\r\n',...
'%%           First version. INITIALS\r\n',...
'%%\r\n',...
'%% TODO\r\n',...
'%%   LIST\r\n',...
'%%\r\n',...
'%%\r\n',...
'%%%% Function Begin!\r\n',...
'\r\n',...
'\r\n',...
'\r\n',...
'end\r\n'];

fileID = fopen([fpath, fname],'w');
funcname = fname(1:end-2);
fprintf(fileID,bptext,funcname);
fclose(fileID);

edit([fpath, fname])

end

